config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/dashboard'
  resources :quizzes
  resources :answers
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :title, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  # Active Record associations
  belongs_to :quizz
  has_many :answers, dependent: :destroy
  # Let a Question having 3 answers
  validates_length_of :answers, maximum: 4
  validates :title, presence: true

end
 

app/models/quizz.rb
class Quizz < ApplicationRecord
  # Active Record associations
  has_many :questions, dependent: :destroy
  # Let a Quizz having 3 questions
  validates_length_of :questions, maximum: 3
  # Active Record validations
    # `difficulty` has to be one of the options
  validates :difficulty, inclusion: { in: ["easy", "medium", "hard"] }
  validates :title, presence: true
  validates :title, length: { in: 3..30,
                    too_long: "30 characters is the maximum allowed" }

  DIFFICULTY = ["easy", "medium", "hard"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true
  
  def email_required?
    false
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_score, only: [:create]
  def create
    # Calling ScoreService to get clean data
    score = ScoreService.new(params).call
    @score = score.first.size
    # result message for user
    @welcome = is_passed?(@score)
    # getting data to send to dashboard via session[:params]
    @quizz = params[:answer].values
    session[:score] = []
    session[:score] << [@quizz, @score]
  end

  private 

  def is_passed?(score)
    return "You passed the test !" if score == 3 || score == 2
    "Sorry buy you failed, try again..."
  end

  def set_score
    @score = 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:home]
  def home
    @quizzes = Quizz.all
  end

  def dashboard
    @scores = []
    @user = current_user
    score = session[:score]
    @scores << [score[0][0][0], score[0][1]]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quizz, only: [:show]
  
  def index
    @quizzes = Quizz.all
  end

  def show
    @questions = @quizz.questions
    @answer = Answer.new
    @good_answer = Answer.where(status: true)
  end

  def create
    @quizz = Quizz.new(quizz_params)
    @quizz.save!
    redirect_to quiz_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_quizz
    @quizz = Quizz.find(params[:id])
  end

  # Never trust parameters from user, only allow the white list through.
  def quizz_params
    params.require(:quizz).permit(:title, :description, :difficulty)
  end
end

app/controllers/score_service.rb
class ScoreService
  def initialize(params)
    @params = params
  end

  def call
    results = []
    params_stringify = @params.to_s
    params_array = params_stringify.split(',')
    results << [params_array[1], params_array[3], params_array[4]]
    str_results = results.join
    cleaned_str = str_results.gsub(/\s+/m, ' ').strip.split(" ").join 
    good_answer = cleaned_str.scan(/(true)/)
    bad_answer = cleaned_str.scan(/(false)/)
    return [good_answer, bad_answer]
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/answers/create.html.erb
<div class="container create_answer">
  <h1><%= @welcome %></h1>

  <p>Your score is <%= @score %></p>

  <%= link_to 'Back Home', root_path, class: 'button' %>
  <%= link_to 'See Dashboard', pages_dashboard_path, class: 'button' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsQuizzator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%# <div class="container"> %>
      <%= yield %>
    <%# </div> %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container dashboard">
  <div class="title">
    <h1>Welcome <%= @user.username %> !</h1>
  </div>
  <div class="user__info">
    <%= image_tag "quizzator_avatar.svg" %>
    <ul>
      <li> Title : <%= @scores[0].first %> ||  Score : <%= @scores[0].last %> </li>
    </ul>
  </div>
</div>

app/views/pages/home.html.erb
<div class="hero">
  <h1>Welcome on Quizzator !</h1>
</div>
<div class="container">
  <div class="quizzes">
    <% @quizzes.each do |quizz| %>
      <div class="quizz">
        <h3> <%= quizz.title %> </h3>
        <p> <%= quizz.description %> </p>
        <%= link_to 'Play', quiz_path(quizz.id), class: 'button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/quizzes/show.html.erb
<div class="container show_quizz">
  <h1> <%= @quizz.title  %> </h1>
  <p class="description"> <%= @quizz.description %> </p>
  <p class="difficulty"> <%= @quizz.difficulty %> </p>
  <%= form_for @answer do |f| %>
    <% @questions.each do |question| %>
    <div class="question">
      <h1><%= question.title %> </h1>
        <% question.answers.each do |answer| %>
          <div class="answer">
            <% "true" ? answer.status == true : answer.status == false %>
            <%= radio_button_tag answer.title, answer.status %>
            <%= answer.title %></br>
          </div>
        <% end %>
    </div>
    <%= f.hidden_field :quizz, value: @quizz.title %>
    <% end %>
  <%= f.submit 'Finish Quizz', class: 'button' %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "quizzator_logo.svg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<% if user_signed_in? %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <%= image_tag "quizzator_avatar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Dashboard", "/pages/dashboard", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
  <% else %>
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
  <% end %>
    </ul>
  </div>
</div>